# Construye el ejecutable
ejercicio1-primes_range: ejercicio1-primes_range.cc 
	g++ -std=c++14 -o ejercicio1-primes_range ejercicio1-primes_range.cc

# Borra el ejecutable
clean: 
	rm -f ejercicio1-primes_range 