MAINS = integer-division triangle maximum-of-three how-many-seconds add-one-second elementos intervals sum-of-digits counting-a sequence-of-collatz logarithms computing-areas

all: $(MAINS)

# Construye los ejecutables
integer-division: ej01-integer-division.cc
	g++ -Wall -std=c++14 -o $@ $^
triangle: ej02-triangle.cc
	g++ -Wall -std=c++14 -o $@ $^
maximum-of-three: ej03-maximum-of-three.cc
	g++ -Wall -std=c++14 -o $@ $^
how-many-seconds: ej04-how-many-seconds.cc
	g++ -Wall -std=c++14 -o $@ $^
add-one-second: ej05-add-one-second.cc 
	g++ -Wall -std=c++14 -o $@ $^
elementos: ej06-elementos.cc
	g++ -Wall -std=c++14 -o $@ $^
intervals: ej07-intervals.cc
	g++ -Wall -std=c++14 -o $@ $^
sum-of-digits: ej08-sum-of-digits.cc
	g++ -Wall -std=c++14 -o $@ $^
counting-a: ej09-counting-a.cc 
	g++ -Wall -std=c++14 -o $@ $^
sequence-of-collatz: ej10-sequence-of-collatz.cc
	g++ -Wall -std=c++14 -o $@ $^
logarithms: ej11-logarithms.cc
	g++ -Wall -std=c++14 -o $@ $^
computing-areas: ej12-computing-areas.cc
	g++ -Wall -std=c++14 -o $@ $^

clean: 
	rm -f integer-division triangle maximum-of-three how-many-seconds add-one-second elementos intervals sum-of-digits counting-a sequence-of-collatz logarithms computing-areas